Traceback (most recent call last):
  File "..\..\..\bin\scripts\repo_update.py", line 209, in <module>
    repo_build(arg.f, arg.t)
  File "..\..\..\bin\scripts\repo_update.py", line 200, in repo_build
    repo_js['patches'][patch_id] = patch_build(
  File "..\..\..\bin\scripts\repo_update.py", line 112, in patch_build
    patch_js = utils.json_load(f_patch_fn)
  File "C:\Users\yeetg\Desktop\toohoo\Touhou 8 - Imperishable Night\thcrap\bin\scripts\utils.py", line 30, in json_load
    return json.load(file, **json_kwargs)
  File "C:\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 11 column 5 (char 246)
